linters:
  flake8:
    exclude: '.tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules'
    max-line-length: 120
  csslint: {  }
  eslint:
    config: './.eslintrc.yml'
  shellcheck:
    shell: bash
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'
fixers:
  enable: false
